# Generated by Django 6.0.1 on 2026-02-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixen', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='rejectionreason',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='rejection_reasons',
            field=models.ManyToManyField(blank=True, to='mixen.rejectionreason'),
        ),
        migrations.AlterField(
            model_name='rejectionreason',
            name='reason',
            field=models.CharField(choices=[('Blurry or unclear images', 'Blurry or unclear images'), ('Face not clearly visible', 'Face not clearly visible'), ('Video does not match photos', 'Video does not match photos'), ('Fake or stolen images', 'Fake or stolen images'), ('Incomplete profile information', 'Incomplete profile information'), ('Multiple people in images', 'Multiple people in images')], max_length=255, unique=True),
        ),
    ]
